BRBLOG_POST_PER_PAGE = 10
BRBLOG_MANAGE_POST_PER_PAGE = 15
BRBLOG_COMMENT_PER_PAGE = 15
BRBLOG_THEMES = {
    'flatly': 'Flatly',
    'litera': 'Litera'
}

SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_RECORD_QUERIES = True
